"use strict";
exports.__esModule = true;
var product_1 = require("./product");
var ProductManager_1 = require("./ProductManager");
var result;
var _productService = new ProductManager_1.ProductManager();
result = _productService.getProducts();
result = _productService.getById(2);
var product = new product_1.Product();
product.name = "IPhone 13";
product.price = 1200;
product.category = "Cell Phone";
_productService.saveProduct(product);
result = _productService.getProducts();
_productService.deleteProduct(product);
result = _productService.getProducts();
product.id = 4;
product.name = "IPhone 12";
product.price = 1100;
product.category = "Cell Phone";
_productService.saveProduct(product);
console.log(result);
